url: http://freshtranslation.com
img_url: http://freshtranslation.com/images
title: Fresh Translation
description: On a Quest to make Fresh Translations.
email: katty@freshtranslation.com
analytics_id: UA-22749258-1
    
exclude: _design, README.textile, Rakefile
destination: _site
lsi: false
pygments: true
markdown: maruku
permalink: pretty
maruku:
  use_tex: false
  use_divs: false
  png_dir: images/latex
  png_url: /images/latex
safe: false
lessc: lessc
